### ISSUE TITLE
VFS filesystem layer

### ISSUE THREAD

**Issue by iefserge** [runtimejs/runtime#1]
Implement VFS filesystem layer. Provide access to initrd filesystem, mount to ``/initrd``.

**Comment by iefserge** [comment]
No longer relevant.

**Comment by piranna** [comment]
> No longer relevant.

Why is it no longer relevant?

**Comment by iefserge** [comment]
@piranna Well, at the moment there is no filesystem and all files need to be bundled up into single javascript bundle using Browserify. I agree, that it would probably be a good idea to support mutable filesystem in a future and have a VFS integrated, but the current implementation I've been working on is no longer fits into overall system design.

**Comment by piranna** [comment]
How works the current implementation? Maybe you could use something like [fatfs](https://github.com/natevw/fatfs) module to have a basic filesystem where to work with...

**Comment by iefserge** [comment]
@piranna fatfs module is very cool, yep, we should be able to use it. This would require virtio disk driver implementation though.

**Comment by piranna** [comment]
You are right, first it should be added a disk driver, if not only possible filesystems would be memory-only.

**Comment by piranna** [comment]
I'm thinking: since fatfs return an object with the same API that the Node.js fs module this could be used as basis for the VFS so there's no need for a "pure" VFS mechanism, you could use the filesystem objects directly, or a filesystem object where other ones could be attached. VFS + FUSE(-ish) system + ad-hoc user defined filesystems all for the same prize :-D
